---
- name: Update pkg cache.
  command: pkg update -f
  environment:
    ASSUME_ALWAYS_YES: "yes"
  tags: ['skip_ansible_lint']

- name: Ensure nginx is installed.
  pkgng:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_package_name }}"

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755
