---
- name: Ensure nginx is installed.
  openbsd_pkg:
    name: "{{ item }}"
    state: present
  with_items: "{{ nginx_package_name }}"

- name: Create logs directory.
  file:
    path: /var/log/nginx
    state: directory
    mode: 0755
